"""add api_url to llm_model_configs

Revision ID: 62cb82f2dc52
Revises: o5p6q7r8s9t0
Create Date: 2026-09-12 09:56:37.851587

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '62cb82f2dc52'
down_revision: Union[str, None] = 'o5p6q7r8s9t0'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_location_profiles_user_id'), table_name='location_profiles')
    op.drop_table('location_profiles')
    op.drop_index(op.f('ix_localith_connections_user_id'), table_name='localith_connections')
    op.drop_table('localith_connections')
    op.drop_index(op.f('ix_location_posts_listing_id'), table_name='location_posts')
    op.drop_index(op.f('ix_location_posts_status'), table_name='location_posts')
    op.drop_index(op.f('ix_location_posts_user_id'), table_name='location_posts')
    op.drop_table('location_posts')
    op.drop_constraint(op.f('channel_verifications_channel_id_key'), 'channel_verifications', type_='unique')
    op.drop_index(op.f('ix_channel_verifications_channel_id'), table_name='channel_verifications')
    op.create_index(op.f('ix_channel_verifications_channel_id'), 'channel_verifications', ['channel_id'], unique=True)
    op.add_column('llm_model_configs', sa.Column('api_url', sa.String(length=500), nullable=True))
    op.drop_index(op.f('ix_intel_reports_user_id'), table_name='review_intelligence_reports')
    op.create_index(op.f('ix_review_intelligence_reports_user_id'), 'review_intelligence_reports', ['user_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_review_intelligence_reports_user_id'), table_name='review_intelligence_reports')
    op.create_index(op.f('ix_intel_reports_user_id'), 'review_intelligence_reports', ['user_id'], unique=False)
    op.drop_column('llm_model_configs', 'api_url')
    op.drop_index(op.f('ix_channel_verifications_channel_id'), table_name='channel_verifications')
    op.create_index(op.f('ix_channel_verifications_channel_id'), 'channel_verifications', ['channel_id'], unique=False)
    op.create_unique_constraint(op.f('channel_verifications_channel_id_key'), 'channel_verifications', ['channel_id'], postgresql_nulls_not_distinct=False)
    op.create_table('location_posts',
    sa.Column('id', sa.VARCHAR(length=36), autoincrement=False, nullable=False),
    sa.Column('user_id', sa.VARCHAR(length=36), autoincrement=False, nullable=False),
    sa.Column('listing_id', sa.VARCHAR(length=64), autoincrement=False, nullable=False),
    sa.Column('location_name', sa.VARCHAR(length=255), autoincrement=False, nullable=True),
    sa.Column('business_name', sa.VARCHAR(length=255), server_default=sa.text("''::character varying"), autoincrement=False, nullable=False),
    sa.Column('title', sa.VARCHAR(length=500), server_default=sa.text("''::character varying"), autoincrement=False, nullable=False),
    sa.Column('post_type', postgresql.ENUM('update', 'event', 'offer', name='post_type'), server_default=sa.text("'update'::post_type"), autoincrement=False, nullable=False),
    sa.Column('description', sa.TEXT(), server_default=sa.text("''::text"), autoincrement=False, nullable=False),
    sa.Column('tags', postgresql.JSON(astext_type=sa.Text()), server_default=sa.text("'[]'::json"), autoincrement=False, nullable=False),
    sa.Column('keywords', postgresql.JSON(astext_type=sa.Text()), server_default=sa.text("'[]'::json"), autoincrement=False, nullable=False),
    sa.Column('image_urls', postgresql.JSON(astext_type=sa.Text()), server_default=sa.text("'[]'::json"), autoincrement=False, nullable=False),
    sa.Column('cta_type', sa.VARCHAR(length=32), autoincrement=False, nullable=True),
    sa.Column('cta_url', sa.VARCHAR(length=1000), autoincrement=False, nullable=True),
    sa.Column('status', postgresql.ENUM('draft', 'scheduled', 'published', 'failed', 'archived', name='post_status'), server_default=sa.text("'draft'::post_status"), autoincrement=False, nullable=False),
    sa.Column('scheduled_on', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=True),
    sa.Column('published_at', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=True),
    sa.Column('localith_response', postgresql.JSON(astext_type=sa.Text()), autoincrement=False, nullable=True),
    sa.Column('error', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=False),
    sa.Column('updated_at', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('location_posts_user_id_fkey'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('location_posts_pkey'))
    )
    op.create_index(op.f('ix_location_posts_user_id'), 'location_posts', ['user_id'], unique=False)
    op.create_index(op.f('ix_location_posts_status'), 'location_posts', ['status'], unique=False)
    op.create_index(op.f('ix_location_posts_listing_id'), 'location_posts', ['listing_id'], unique=False)
    op.create_table('localith_connections',
    sa.Column('id', sa.VARCHAR(length=36), autoincrement=False, nullable=False),
    sa.Column('user_id', sa.VARCHAR(length=36), autoincrement=False, nullable=False),
    sa.Column('listing_id', sa.VARCHAR(length=64), autoincrement=False, nullable=False),
    sa.Column('listing_name', sa.VARCHAR(length=255), autoincrement=False, nullable=False),
    sa.Column('listing_google_id', sa.VARCHAR(length=128), autoincrement=False, nullable=True),
    sa.Column('last_synced_at', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=False),
    sa.Column('updated_at', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=False),
    sa.Column('address', sa.VARCHAR(length=500), autoincrement=False, nullable=True),
    sa.Column('phone_number', sa.VARCHAR(length=64), autoincrement=False, nullable=True),
    sa.Column('website_url', sa.VARCHAR(length=500), autoincrement=False, nullable=True),
    sa.Column('maps_url', sa.VARCHAR(length=500), autoincrement=False, nullable=True),
    sa.Column('store_code', sa.VARCHAR(length=128), autoincrement=False, nullable=True),
    sa.Column('is_verified', sa.BOOLEAN(), autoincrement=False, nullable=True),
    sa.Column('is_disabled', sa.BOOLEAN(), autoincrement=False, nullable=True),
    sa.Column('is_suspended', sa.BOOLEAN(), autoincrement=False, nullable=True),
    sa.Column('total_reviews', sa.INTEGER(), server_default=sa.text('0'), autoincrement=False, nullable=False),
    sa.Column('average_rating', sa.DOUBLE_PRECISION(precision=53), server_default=sa.text("'0'::double precision"), autoincrement=False, nullable=False),
    sa.Column('last_review_on', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=True),
    sa.Column('last_reply_on', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=True),
    sa.Column('raw_listing_json', postgresql.JSON(astext_type=sa.Text()), autoincrement=False, nullable=True),
    sa.Column('profile_synced_at', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=True),
    sa.Column('raw_metrics_json', postgresql.JSON(astext_type=sa.Text()), autoincrement=False, nullable=True),
    sa.Column('raw_item_metrics_json', postgresql.JSON(astext_type=sa.Text()), autoincrement=False, nullable=True),
    sa.Column('metrics_start', sa.DATE(), autoincrement=False, nullable=True),
    sa.Column('metrics_end', sa.DATE(), autoincrement=False, nullable=True),
    sa.Column('metrics_synced_at', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('localith_connections_user_id_fkey'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('localith_connections_pkey')),
    sa.UniqueConstraint('user_id', name=op.f('uq_localith_user'), postgresql_include=[], postgresql_nulls_not_distinct=False)
    )
    op.create_index(op.f('ix_localith_connections_user_id'), 'localith_connections', ['user_id'], unique=False)
    op.create_table('location_profiles',
    sa.Column('id', sa.VARCHAR(length=36), autoincrement=False, nullable=False),
    sa.Column('user_id', sa.VARCHAR(length=36), autoincrement=False, nullable=False),
    sa.Column('listing_id', sa.VARCHAR(length=64), autoincrement=False, nullable=False),
    sa.Column('description', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('categories', postgresql.JSON(astext_type=sa.Text()), server_default=sa.text("'{}'::json"), autoincrement=False, nullable=False),
    sa.Column('hours', postgresql.JSON(astext_type=sa.Text()), server_default=sa.text("'{}'::json"), autoincrement=False, nullable=False),
    sa.Column('service_area', postgresql.JSON(astext_type=sa.Text()), server_default=sa.text("'[]'::json"), autoincrement=False, nullable=False),
    sa.Column('attributes', postgresql.JSON(astext_type=sa.Text()), server_default=sa.text("'{}'::json"), autoincrement=False, nullable=False),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=False),
    sa.Column('updated_at', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('location_profiles_user_id_fkey'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('location_profiles_pkey')),
    sa.UniqueConstraint('user_id', 'listing_id', name=op.f('uq_location_profile_listing'), postgresql_include=[], postgresql_nulls_not_distinct=False)
    )
    op.create_index(op.f('ix_location_profiles_user_id'), 'location_profiles', ['user_id'], unique=False)
    # ### end Alembic commands ###
