"""add localith_posts tables

Revision ID: ee912c4e504d
Revises: 86902087ebae
Create Date: 2026-09-12 10:44:39.462944

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'ee912c4e504d'
down_revision: Union[str, None] = '86902087ebae'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('localith_connections',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('user_id', sa.String(length=36), nullable=False),
    sa.Column('listing_id', sa.String(length=64), nullable=False),
    sa.Column('listing_name', sa.String(length=255), nullable=False),
    sa.Column('listing_google_id', sa.String(length=128), nullable=True),
    sa.Column('last_synced_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('address', sa.String(length=500), nullable=True),
    sa.Column('phone_number', sa.String(length=64), nullable=True),
    sa.Column('website_url', sa.String(length=500), nullable=True),
    sa.Column('maps_url', sa.String(length=500), nullable=True),
    sa.Column('store_code', sa.String(length=128), nullable=True),
    sa.Column('is_verified', sa.Boolean(), nullable=True),
    sa.Column('is_disabled', sa.Boolean(), nullable=True),
    sa.Column('is_suspended', sa.Boolean(), nullable=True),
    sa.Column('total_reviews', sa.Integer(), nullable=False),
    sa.Column('average_rating', sa.Float(), nullable=False),
    sa.Column('last_review_on', sa.DateTime(timezone=True), nullable=True),
    sa.Column('last_reply_on', sa.DateTime(timezone=True), nullable=True),
    sa.Column('raw_listing_json', sa.JSON(), nullable=True),
    sa.Column('profile_synced_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('raw_metrics_json', sa.JSON(), nullable=True),
    sa.Column('raw_item_metrics_json', sa.JSON(), nullable=True),
    sa.Column('metrics_start', sa.Date(), nullable=True),
    sa.Column('metrics_end', sa.Date(), nullable=True),
    sa.Column('metrics_synced_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id', name='uq_localith_user')
    )
    op.create_index(op.f('ix_localith_connections_user_id'), 'localith_connections', ['user_id'], unique=False)
    op.create_table('location_posts',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('user_id', sa.String(length=36), nullable=False),
    sa.Column('listing_id', sa.String(length=64), nullable=False),
    sa.Column('location_name', sa.String(length=255), nullable=True),
    sa.Column('business_name', sa.String(length=255), nullable=False),
    sa.Column('title', sa.String(length=500), nullable=False),
     sa.Column('post_type', sa.Enum('update', 'event', 'offer', name='post_type', create_type=False), nullable=False),
     sa.Column('description', sa.Text(), nullable=False),
     sa.Column('tags', sa.JSON(), nullable=False),
     sa.Column('keywords', sa.JSON(), nullable=False),
     sa.Column('image_urls', sa.JSON(), nullable=False),
     sa.Column('cta_type', sa.String(length=32), nullable=True),
     sa.Column('cta_url', sa.String(length=1000), nullable=True),
     sa.Column('status', sa.Enum('draft', 'scheduled', 'published', 'failed', 'archived', name='post_status', create_type=False), nullable=False),
    sa.Column('scheduled_on', sa.DateTime(timezone=True), nullable=True),
    sa.Column('published_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('localith_response', sa.JSON(), nullable=True),
    sa.Column('error', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_location_posts_listing_id'), 'location_posts', ['listing_id'], unique=False)
    op.create_index(op.f('ix_location_posts_status'), 'location_posts', ['status'], unique=False)
    op.create_index(op.f('ix_location_posts_user_id'), 'location_posts', ['user_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_location_posts_user_id'), table_name='location_posts')
    op.drop_index(op.f('ix_location_posts_status'), table_name='location_posts')
    op.drop_index(op.f('ix_location_posts_listing_id'), table_name='location_posts')
    op.drop_table('location_posts')
    op.drop_index(op.f('ix_localith_connections_user_id'), table_name='localith_connections')
    op.drop_table('localith_connections')
    # ### end Alembic commands ###
